### ISSUE TITLE
Modelo Mínimo de Bergman y perturbaciones

### ISSUE THREAD

**Issue by marinasainz** [marinasainz/TFG-Marina-Sainz#12]
Se ha trabajado con el Modelo Mínimo para estudiar el comportamiento de la glucosa en el organismo. Para una mayor comprensión, se han introducido variables como la administración de insulina exógena, la realización del ejercicio físico y el consumo de carbohidratos.

**Comment by marinasainz** [comment]
La ingesta de comida se mide para este estudio mediante el consumo de carbohidratos, que aumentan los niveles de glucosa. Se trabaja con ayuno e ingesta para comparar el efecto de las variables.

**Comment by marinasainz** [comment]
La administración de insulina externa permite disminuir inmediatamente los niveles de glucosa en el organismo. Sin embargo, una administración descontrolada puede derivar en hiperglucemias e hipoglucemias.

**Comment by marinasainz** [comment]
Pertubación de la ingesta obtenida.

**Comment by PereMF** [comment]
Buenos días, Marina, @marinasainz 

Ante todo, muchas gracias por compartir tus investigaciones, he leído detenidamente tu TFG, me ha sorprendido la facilidad que tienes a la hora de explicarte, se entiendo todo muy bien, te felicito. Has transferido muy bien tu conocimiento. :)

Con tu experiencia, te quería lanzarte unas cuestiones: 
- Comentas que la función de entrada del ejercicio físico que has utilizado es muy sencilla (opino lo mismo), ¿tienes en mente otra un poco más compleja que te podría haber dado pie a más análisis?
- En relación a la entrada de insulina, he visto que utilizas rampas, ¿alguna otra idea de formulación? Si pudieras darme más información, sería de agradecer. No me parece mala idea. Por lo leído lo has hecho para simular un tiempo de absorción y eliminación, para poder simular un tipo de retraso. Una rampa ascendente hasta un tiempo determinado Tmax y una rampa descendeste desde el Tmax. No he visto los tiempos Tmax introducidos en la simulación. 
- Y una última, ¿si tuvieras que incluir una función de entrada de temperatura para simular otro tipo de estrés físico, con cual estarías pensando?

Por cierto, no hay prisa en contestar, todos vamos siempre muy ocupados...

Muchas gracias por compartir tu conocimiento. Te he enviado por LinkedIn estar en contacto (Pere). Saludos
PD: estoy realizando una tesis doctoral relacionada con el asunto
